"""
NetPulse PCAP Analyzer.

Reads offline .pcap / .pcapng files generated by Wireshark, filters for TCP
and UDP packets on the configured experiment port, prints per-packet details,
and computes summary statistics (packet counts, TCP handshake pairs, average sizes).

Usage:
    python analyzer/pcap_parser.py                      # analyzes data/capture.pcap
    python analyzer/pcap_parser.py path/to/file.pcap     # analyzes specific pcap
    python analyzer/pcap_parser.py --generate-sample     # generates sample pcap & analyzes
"""

import argparse
import os
import sys
import time
import yaml
from datetime import datetime

# Project root
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scapy.all import IP, TCP, UDP, Ether, Raw, rdpcap, wrpcap


def load_config() -> dict:
    config_path = os.path.join(ROOT, "config.yaml")
    with open(config_path) as f:
        return yaml.safe_load(f)


def format_flags(tcp_layer) -> str:
    """Format TCP flags into human-readable representation."""
    flags_str = str(tcp_layer.flags)
    flag_names = []
    if "S" in flags_str:
        flag_names.append("SYN")
    if "A" in flags_str:
        flag_names.append("ACK")
    if "P" in flags_str:
        flag_names.append("PSH")
    if "F" in flags_str:
        flag_names.append("FIN")
    if "R" in flags_str:
        flag_names.append("RST")
    return "+".join(flag_names) if flag_names else flags_str


def generate_sample_pcap(filepath: str, target_port: int = 5000):
    """Generate a sample .pcap file with TCP handshakes and UDP datagrams for testing."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    pkts = []
    client_ip = "127.0.0.1"
    server_ip = "127.0.0.1"
    client_port = 54321

    t0 = time.time()

    # 1. TCP Handshake
    syn = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="S", seq=1000)
    syn.time = t0
    pkts.append(syn)

    syn_ack = Ether() / IP(src=server_ip, dst=client_ip) / TCP(sport=target_port, dport=client_port, flags="SA", seq=2000, ack=1001)
    syn_ack.time = t0 + 0.001
    pkts.append(syn_ack)

    ack = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="A", seq=1001, ack=2001)
    ack.time = t0 + 0.002
    pkts.append(ack)

    # 2. TCP Data Echo
    tcp_data = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="PA", seq=1001, ack=2001) / Raw(b"X" * 64)
    tcp_data.time = t0 + 0.005
    pkts.append(tcp_data)

    tcp_echo = Ether() / IP(src=server_ip, dst=client_ip) / TCP(sport=target_port, dport=client_port, flags="PA", seq=2001, ack=1065) / Raw(b"X" * 64)
    tcp_echo.time = t0 + 0.006
    pkts.append(tcp_echo)

    # 3. TCP Teardown
    fin = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="FA", seq=1065, ack=2065)
    fin.time = t0 + 0.010
    pkts.append(fin)

    # 4. UDP Datagram Echo
    udp_req = Ether() / IP(src=client_ip, dst=server_ip) / UDP(sport=client_port, dport=target_port) / Raw(b"U" * 256)
    udp_req.time = t0 + 0.015
    pkts.append(udp_req)

    udp_resp = Ether() / IP(src=server_ip, dst=client_ip) / UDP(sport=target_port, dport=client_port) / Raw(b"U" * 256)
    udp_resp.time = t0 + 0.016
    pkts.append(udp_resp)

    wrpcap(filepath, pkts)
    print(f"[PCAP Analyzer] Sample PCAP generated at: {filepath} ({len(pkts)} packets)")


def parse_pcap(pcap_path: str, target_port: int):
    """Read and parse a .pcap file, outputting packet details and protocol statistics."""
    if not os.path.exists(pcap_path):
        print(f"[Error] PCAP file not found at: {pcap_path}")
        print("Tip: Run 'python analyzer/pcap_parser.py --generate-sample' to create a test file.")
        return

    print(f"\n{'=' * 80}")
    print(f"  NETPULSE PCAP ANALYZER — File: {pcap_path}")
    print(f"  Filtering for Target Port: {target_port}")
    print(f"{'=' * 80}\n")

    try:
        packets = rdpcap(pcap_path)
    except Exception as e:
        print(f"[Error] Failed to read PCAP file: {e}")
        return

    tcp_count = 0
    udp_count = 0
    tcp_total_bytes = 0
    udp_total_bytes = 0

    # Tracking TCP handshake pairs
    syn_seen = 0
    syn_ack_seen = 0
    ack_after_synack = 0
    handshake_pairs = 0

    print(f"{'No.':<5} {'Protocol':<8} {'Source IP:Port':<22} {'Dest IP:Port':<22} {'Size(B)':<8} {'Flags/Info':<15}")
    print("─" * 80)

    for idx, pkt in enumerate(packets, start=1):
        if not pkt.haslayer(IP):
            continue

        ip_layer = pkt[IP]
        src_ip = ip_layer.src
        dst_ip = ip_layer.dst

        if pkt.haslayer(TCP):
            tcp = pkt[TCP]
            if tcp.sport != target_port and tcp.dport != target_port:
                continue

            tcp_count += 1
            pkt_size = len(pkt)
            tcp_total_bytes += pkt_size
            flags = format_flags(tcp)

            # Handshake tracking logic
            if "SYN" in flags and "ACK" not in flags:
                syn_seen += 1
            elif "SYN" in flags and "ACK" in flags:
                syn_ack_seen += 1
            elif "ACK" in flags and syn_ack_seen > handshake_pairs:
                ack_after_synack += 1
                handshake_pairs += 1

            info = f"Seq={tcp.seq} Ack={tcp.ack} [{flags}]"
            src_str = f"{src_ip}:{tcp.sport}"
            dst_str = f"{dst_ip}:{tcp.dport}"

            print(f"{idx:<5} {'TCP':<8} {src_str:<22} {dst_str:<22} {pkt_size:<8} {info:<15}")

        elif pkt.haslayer(UDP):
            udp = pkt[UDP]
            if udp.sport != target_port and udp.dport != target_port:
                continue

            udp_count += 1
            pkt_size = len(pkt)
            udp_total_bytes += pkt_size

            src_str = f"{src_ip}:{udp.sport}"
            dst_str = f"{dst_ip}:{udp.dport}"
            info = f"Len={udp.len}"

            print(f"{idx:<5} {'UDP':<8} {src_str:<22} {dst_str:<22} {pkt_size:<8} {info:<15}")

    # Summary report
    avg_tcp_size = (tcp_total_bytes / tcp_count) if tcp_count > 0 else 0
    avg_udp_size = (udp_total_bytes / udp_count) if udp_count > 0 else 0

    print(f"\n{'=' * 80}")
    print("  PACKET CAPTURE SUMMARY")
    print(f"{'=' * 80}")
    print(f"  Total Relevant Packets Filtered : {tcp_count + udp_count}")
    print(f"  TCP Packet Count                 : {tcp_count}")
    print(f"  UDP Packet Count                 : {udp_count}")
    print(f"  Average TCP Packet Size          : {avg_tcp_size:.2f} bytes")
    print(f"  Average UDP Packet Size          : {avg_udp_size:.2f} bytes")
    print(f"  Complete TCP Handshakes Detected : {handshake_pairs}")
    print(f"{'=' * 80}\n")


def main():
    parser = argparse.ArgumentParser(description="NetPulse Wireshark PCAP Analyzer")
    parser.add_argument("pcap_file", nargs="?", default=os.path.join(ROOT, "data", "capture.pcap"),
                        help="Path to .pcap or .pcapng file (default: data/capture.pcap)")
    parser.add_argument("--generate-sample", action="store_true",
                        help="Generate a sample .pcap file for testing and exit")
    args = parser.parse_args()

    cfg = load_config()
    target_port = cfg.get("server_port", 5000)

    sample_path = os.path.join(ROOT, "data", "sample_capture.pcap")

    if args.generate_sample:
        generate_sample_pcap(sample_path, target_port)
        parse_pcap(sample_path, target_port)
        return

    # If default file doesn't exist, generate sample & parse it for a seamless demo
    if args.pcap_file == os.path.join(ROOT, "data", "capture.pcap") and not os.path.exists(args.pcap_file):
        print(f"[Runner] No capture file found at '{args.pcap_file}'. Generating sample PCAP for demo...")
        generate_sample_pcap(sample_path, target_port)
        parse_pcap(sample_path, target_port)
    else:
        parse_pcap(args.pcap_file, target_port)


if __name__ == "__main__":
    main()
