"""
NetPulse PCAP Analyzer.

Reads offline .pcap / .pcapng files generated by Wireshark, filters for TCP
and UDP packets on the configured experiment port, prints per-packet details,
and computes summary statistics (packet counts, TCP handshake pairs, average sizes).

Usage:
    python analyzer/pcap_parser.py                      # analyzes data/capture.pcap
    python analyzer/pcap_parser.py path/to/file.pcap     # analyzes specific pcap
"""

import argparse
import os
import sys
import time
import pandas as pd
import yaml

# Project root
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scapy.all import IP, TCP, UDP, rdpcap


def load_config() -> dict:
    config_path = os.path.join(ROOT, "config.yaml")
    if os.path.exists(config_path):
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {"server_port": 5001}


def format_flags(tcp_layer) -> str:
    """Format TCP flags into human-readable representation."""
    flags_str = str(tcp_layer.flags)
    flag_names = []
    if "S" in flags_str:
        flag_names.append("SYN")
    if "A" in flags_str:
        flag_names.append("ACK")
    if "P" in flags_str:
        flag_names.append("PSH")
    if "F" in flags_str:
        flag_names.append("FIN")
    if "R" in flags_str:
        flag_names.append("RST")
    return "+".join(flag_names) if flag_names else flags_str


def parse_pcap_data(pcap_path: str, target_port: int):
    """
    Read and parse a .pcap file, returning a pandas DataFrame and summary stats.

    Returns:
        (df, summary_dict)
    """
    if not os.path.exists(pcap_path):
        return pd.DataFrame(), {}

    try:
        packets = rdpcap(pcap_path)
    except Exception as e:
        print(f"[Error] Failed to read PCAP file: {e}")
        return pd.DataFrame(), {}

    rows = []
    tcp_count = 0
    udp_count = 0
    tcp_total_bytes = 0
    udp_total_bytes = 0

    syn_seen = 0
    syn_ack_seen = 0
    handshake_pairs = 0

    idx = 1
    for pkt in packets:
        if not pkt.haslayer(IP):
            continue

        ip_layer = pkt[IP]
        src_ip = ip_layer.src
        dst_ip = ip_layer.dst

        if pkt.haslayer(TCP):
            tcp = pkt[TCP]
            if target_port and target_port > 0:
                if tcp.sport != target_port and tcp.dport != target_port:
                    continue

            tcp_count += 1
            pkt_size = len(pkt)
            tcp_total_bytes += pkt_size
            flags = format_flags(tcp)

            if "SYN" in flags and "ACK" not in flags:
                syn_seen += 1
            elif "SYN" in flags and "ACK" in flags:
                syn_ack_seen += 1
            elif "ACK" in flags and syn_ack_seen > handshake_pairs:
                handshake_pairs += 1

            rows.append({
                "No.": idx,
                "Protocol": "TCP",
                "Source": f"{src_ip}:{tcp.sport}",
                "Destination": f"{dst_ip}:{tcp.dport}",
                "Length (B)": pkt_size,
                "Timestamp": float(pkt.time),
                "Flags": flags,
                "Seq": tcp.seq,
                "Ack": tcp.ack,
                "Info": f"Seq={tcp.seq} Ack={tcp.ack} [{flags}]",
            })
            idx += 1

        elif pkt.haslayer(UDP):
            udp = pkt[UDP]
            if target_port and target_port > 0:
                if udp.sport != target_port and udp.dport != target_port:
                    continue

            udp_count += 1
            pkt_size = len(pkt)
            udp_total_bytes += pkt_size

            rows.append({
                "No.": idx,
                "Protocol": "UDP",
                "Source": f"{src_ip}:{udp.sport}",
                "Destination": f"{dst_ip}:{udp.dport}",
                "Length (B)": pkt_size,
                "Timestamp": float(pkt.time),
                "Flags": "N/A",
                "Seq": "N/A",
                "Ack": "N/A",
                "Info": f"Len={udp.len}",
            })
            idx += 1

    df = pd.DataFrame(rows)
    avg_tcp_size = (tcp_total_bytes / tcp_count) if tcp_count > 0 else 0
    avg_udp_size = (udp_total_bytes / udp_count) if udp_count > 0 else 0

    summary = {
        "total_packets": tcp_count + udp_count,
        "tcp_count": tcp_count,
        "udp_count": udp_count,
        "avg_tcp_size": round(avg_tcp_size, 2),
        "avg_udp_size": round(avg_udp_size, 2),
        "handshake_pairs": handshake_pairs,
    }

    return df, summary


def pcap_to_metrics(packet_df: pd.DataFrame) -> pd.DataFrame:
    """Convert parsed PCAP packets into dashboard metric rows."""
    columns = [
        "Protocol", "PacketSize", "Packets", "TransmissionTime", "AvgRTT",
        "Throughput", "PacketLoss", "Jitter",
    ]
    if packet_df.empty:
        return pd.DataFrame(columns=columns)

    ordered_packets = packet_df.sort_values("Timestamp")
    metric_rows = []
    for (protocol, packet_size), group in packet_df.groupby(["Protocol", "Length (B)"]):
        timestamps = group["Timestamp"].sort_values().to_numpy()
        elapsed = max(float(timestamps[-1] - timestamps[0]), 0.000001)
        intervals_ms = pd.Series(timestamps).diff().dropna() * 1000
        rtt_samples = []
        for _, packet in group.iterrows():
            response = ordered_packets[
                (ordered_packets["Protocol"] == protocol)
                & (ordered_packets["Source"] == packet["Destination"])
                & (ordered_packets["Destination"] == packet["Source"])
                & (ordered_packets["Timestamp"] > packet["Timestamp"])
            ]
            if not response.empty:
                rtt_samples.append((response.iloc[0]["Timestamp"] - packet["Timestamp"]) * 1000)

        metric_rows.append({
            "Protocol": protocol,
            "PacketSize": int(packet_size),
            "Packets": len(group),
            "TransmissionTime": elapsed,
            "AvgRTT": float(pd.Series(rtt_samples).mean()) if rtt_samples else 0.0,
            "Throughput": (len(group) * packet_size * 8) / elapsed / 1_000_000,
            "PacketLoss": 0.0,
            "Jitter": float(intervals_ms.diff().abs().mean()) if len(intervals_ms) > 1 else 0.0,
        })

    return pd.DataFrame(metric_rows, columns=columns)


def parse_pcap(pcap_path: str, target_port: int):
    """Read and parse a .pcap file, outputting packet details and protocol statistics."""
    if not os.path.exists(pcap_path):
        print(f"[Error] PCAP file not found at: {pcap_path}")
        return

    print(f"\n{'=' * 80}")
    print(f"  NETPULSE PCAP ANALYZER — File: {pcap_path}")
    print(f"  Filtering for Target Port: {target_port}")
    print(f"{'=' * 80}\n")

    df, summary = parse_pcap_data(pcap_path, target_port)
    if df.empty:
        print("[Notice] No relevant TCP/UDP packets found matching port.")
        return

    print(f"{'No.':<5} {'Protocol':<8} {'Source IP:Port':<22} {'Dest IP:Port':<22} {'Size(B)':<8} {'Flags/Info':<15}")
    print("─" * 80)

    for _, row in df.iterrows():
        print(f"{row['No.']:<5} {row['Protocol']:<8} {row['Source']:<22} {row['Destination']:<22} {row['Length (B)']:<8} {row['Info']:<15}")

    print(f"\n{'=' * 80}")
    print("  PACKET CAPTURE SUMMARY")
    print(f"{'=' * 80}")
    print(f"  Total Relevant Packets Filtered : {summary['total_packets']}")
    print(f"  TCP Packet Count                 : {summary['tcp_count']}")
    print(f"  UDP Packet Count                 : {summary['udp_count']}")
    print(f"  Average TCP Packet Size          : {summary['avg_tcp_size']} bytes")
    print(f"  Average UDP Packet Size          : {summary['avg_udp_size']} bytes")
    print(f"  Complete TCP Handshakes Detected : {summary['handshake_pairs']}")
    print(f"{'=' * 80}\n")


def main():
    parser = argparse.ArgumentParser(description="NetPulse Wireshark PCAP Analyzer")
    parser.add_argument("pcap_file", nargs="?", default=os.path.join(ROOT, "data", "capture.pcap"),
                        help="Path to .pcap or .pcapng file (default: data/capture.pcap)")
    args = parser.parse_args()

    cfg = load_config()
    target_port = cfg.get("server_port", 5001)

    parse_pcap(args.pcap_file, target_port)


if __name__ == "__main__":
    main()
