"""
NetPulse PCAP Analyzer.

Reads offline .pcap / .pcapng files generated by Wireshark, filters for TCP
and UDP packets on the configured experiment port, prints per-packet details,
and computes summary statistics (packet counts, TCP handshake pairs, average sizes).

Usage:
    python analyzer/pcap_parser.py                      # analyzes data/capture.pcap
    python analyzer/pcap_parser.py path/to/file.pcap     # analyzes specific pcap
    python analyzer/pcap_parser.py --generate-sample     # generates sample pcap & analyzes
"""

import argparse
import os
import sys
import time
import pandas as pd
import yaml

# Project root
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scapy.all import IP, TCP, UDP, Ether, Raw, rdpcap, wrpcap


def load_config() -> dict:
    config_path = os.path.join(ROOT, "config.yaml")
    if os.path.exists(config_path):
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {"server_port": 5000}


def format_flags(tcp_layer) -> str:
    """Format TCP flags into human-readable representation."""
    flags_str = str(tcp_layer.flags)
    flag_names = []
    if "S" in flags_str:
        flag_names.append("SYN")
    if "A" in flags_str:
        flag_names.append("ACK")
    if "P" in flags_str:
        flag_names.append("PSH")
    if "F" in flags_str:
        flag_names.append("FIN")
    if "R" in flags_str:
        flag_names.append("RST")
    return "+".join(flag_names) if flag_names else flags_str


def generate_sample_pcap(filepath: str, target_port: int = 5000):
    """Generate a sample .pcap file with TCP handshakes and UDP datagrams for testing."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    pkts = []
    client_ip = "127.0.0.1"
    server_ip = "127.0.0.1"
    client_port = 54321

    t0 = time.time()

    # 1. TCP Handshake
    syn = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="S", seq=1000)
    syn.time = t0
    pkts.append(syn)

    syn_ack = Ether() / IP(src=server_ip, dst=client_ip) / TCP(sport=target_port, dport=client_port, flags="SA", seq=2000, ack=1001)
    syn_ack.time = t0 + 0.001
    pkts.append(syn_ack)

    ack = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="A", seq=1001, ack=2001)
    ack.time = t0 + 0.002
    pkts.append(ack)

    # 2. TCP Data Echo
    tcp_data = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="PA", seq=1001, ack=2001) / Raw(b"X" * 64)
    tcp_data.time = t0 + 0.005
    pkts.append(tcp_data)

    tcp_echo = Ether() / IP(src=server_ip, dst=client_ip) / TCP(sport=target_port, dport=client_port, flags="PA", seq=2001, ack=1065) / Raw(b"X" * 64)
    tcp_echo.time = t0 + 0.006
    pkts.append(tcp_echo)

    # 3. TCP Teardown
    fin = Ether() / IP(src=client_ip, dst=server_ip) / TCP(sport=client_port, dport=target_port, flags="FA", seq=1065, ack=2065)
    fin.time = t0 + 0.010
    pkts.append(fin)

    # 4. UDP Datagram Echo
    udp_req = Ether() / IP(src=client_ip, dst=server_ip) / UDP(sport=client_port, dport=target_port) / Raw(b"U" * 256)
    udp_req.time = t0 + 0.015
    pkts.append(udp_req)

    udp_resp = Ether() / IP(src=server_ip, dst=client_ip) / UDP(sport=target_port, dport=client_port) / Raw(b"U" * 256)
    udp_resp.time = t0 + 0.016
    pkts.append(udp_resp)

    wrpcap(filepath, pkts)
    print(f"[PCAP Analyzer] Sample PCAP generated at: {filepath} ({len(pkts)} packets)")


def parse_pcap_data(pcap_path: str, target_port: int):
    """
    Read and parse a .pcap file, returning a pandas DataFrame and summary stats.

    Returns:
        (df, summary_dict)
    """
    if not os.path.exists(pcap_path):
        return pd.DataFrame(), {}

    try:
        packets = rdpcap(pcap_path)
    except Exception as e:
        print(f"[Error] Failed to read PCAP file: {e}")
        return pd.DataFrame(), {}

    rows = []
    tcp_count = 0
    udp_count = 0
    tcp_total_bytes = 0
    udp_total_bytes = 0

    syn_seen = 0
    syn_ack_seen = 0
    handshake_pairs = 0

    idx = 1
    for pkt in packets:
        if not pkt.haslayer(IP):
            continue

        ip_layer = pkt[IP]
        src_ip = ip_layer.src
        dst_ip = ip_layer.dst

        if pkt.haslayer(TCP):
            tcp = pkt[TCP]
            if tcp.sport != target_port and tcp.dport != target_port:
                continue

            tcp_count += 1
            pkt_size = len(pkt)
            tcp_total_bytes += pkt_size
            flags = format_flags(tcp)

            if "SYN" in flags and "ACK" not in flags:
                syn_seen += 1
            elif "SYN" in flags and "ACK" in flags:
                syn_ack_seen += 1
            elif "ACK" in flags and syn_ack_seen > handshake_pairs:
                handshake_pairs += 1

            rows.append({
                "No.": idx,
                "Protocol": "TCP",
                "Source": f"{src_ip}:{tcp.sport}",
                "Destination": f"{dst_ip}:{tcp.dport}",
                "Length (B)": pkt_size,
                "Flags": flags,
                "Seq": tcp.seq,
                "Ack": tcp.ack,
                "Info": f"Seq={tcp.seq} Ack={tcp.ack} [{flags}]",
            })
            idx += 1

        elif pkt.haslayer(UDP):
            udp = pkt[UDP]
            if udp.sport != target_port and udp.dport != target_port:
                continue

            udp_count += 1
            pkt_size = len(pkt)
            udp_total_bytes += pkt_size

            rows.append({
                "No.": idx,
                "Protocol": "UDP",
                "Source": f"{src_ip}:{udp.sport}",
                "Destination": f"{dst_ip}:{udp.dport}",
                "Length (B)": pkt_size,
                "Flags": "N/A",
                "Seq": "N/A",
                "Ack": "N/A",
                "Info": f"Len={udp.len}",
            })
            idx += 1

    df = pd.DataFrame(rows)
    avg_tcp_size = (tcp_total_bytes / tcp_count) if tcp_count > 0 else 0
    avg_udp_size = (udp_total_bytes / udp_count) if udp_count > 0 else 0

    summary = {
        "total_packets": tcp_count + udp_count,
        "tcp_count": tcp_count,
        "udp_count": udp_count,
        "avg_tcp_size": round(avg_tcp_size, 2),
        "avg_udp_size": round(avg_udp_size, 2),
        "handshake_pairs": handshake_pairs,
    }

    return df, summary


def parse_pcap(pcap_path: str, target_port: int):
    """Read and parse a .pcap file, outputting packet details and protocol statistics."""
    if not os.path.exists(pcap_path):
        print(f"[Error] PCAP file not found at: {pcap_path}")
        print("Tip: Run 'python analyzer/pcap_parser.py --generate-sample' to create a test file.")
        return

    print(f"\n{'=' * 80}")
    print(f"  NETPULSE PCAP ANALYZER — File: {pcap_path}")
    print(f"  Filtering for Target Port: {target_port}")
    print(f"{'=' * 80}\n")

    df, summary = parse_pcap_data(pcap_path, target_port)
    if df.empty:
        print("[Notice] No relevant TCP/UDP packets found matching port.")
        return

    print(f"{'No.':<5} {'Protocol':<8} {'Source IP:Port':<22} {'Dest IP:Port':<22} {'Size(B)':<8} {'Flags/Info':<15}")
    print("─" * 80)

    for _, row in df.iterrows():
        print(f"{row['No.']:<5} {row['Protocol']:<8} {row['Source']:<22} {row['Destination']:<22} {row['Length (B)']:<8} {row['Info']:<15}")

    print(f"\n{'=' * 80}")
    print("  PACKET CAPTURE SUMMARY")
    print(f"{'=' * 80}")
    print(f"  Total Relevant Packets Filtered : {summary['total_packets']}")
    print(f"  TCP Packet Count                 : {summary['tcp_count']}")
    print(f"  UDP Packet Count                 : {summary['udp_count']}")
    print(f"  Average TCP Packet Size          : {summary['avg_tcp_size']} bytes")
    print(f"  Average UDP Packet Size          : {summary['avg_udp_size']} bytes")
    print(f"  Complete TCP Handshakes Detected : {summary['handshake_pairs']}")
    print(f"{'=' * 80}\n")


def main():
    parser = argparse.ArgumentParser(description="NetPulse Wireshark PCAP Analyzer")
    parser.add_argument("pcap_file", nargs="?", default=os.path.join(ROOT, "data", "capture.pcap"),
                        help="Path to .pcap or .pcapng file (default: data/capture.pcap)")
    parser.add_argument("--generate-sample", action="store_true",
                        help="Generate a sample .pcap file for testing and exit")
    args = parser.parse_args()

    cfg = load_config()
    target_port = cfg.get("server_port", 5000)

    sample_path = os.path.join(ROOT, "data", "sample_capture.pcap")

    if args.generate-sample or args.generate_sample:
        generate_sample_pcap(sample_path, target_port)
        parse_pcap(sample_path, target_port)
        return

    if args.pcap_file == os.path.join(ROOT, "data", "capture.pcap") and not os.path.exists(args.pcap_file):
        print(f"[Runner] No capture file found at '{args.pcap_file}'. Generating sample PCAP for demo...")
        generate_sample_pcap(sample_path, target_port)
        parse_pcap(sample_path, target_port)
    else:
        parse_pcap(args.pcap_file, target_port)


if __name__ == "__main__":
    main()
